export default Data = [
  {
    name: 'Development',
    course: 'Adobe illustrator for  \n all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 11,
    category: 'Development',
    status: 'Online',
  },
  {
    name: 'Teaching',
    course: 'Adobe illustrator for  \n all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 12,
    category: 'Teaching',
    status: 'Offline',
  },
  {
    name: 'Computer',
    course: 'Adobe illustrator for  \n all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 13,
    category: 'Computer',
    status: 'F2F',
  },
  {
    name: 'Teaching1',
    course: 'Adobe illustrator for  \n all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 14,
    category: 'Development',
    status: 'Online',
  },
  {
    name: 'Computer1',
    course: 'Adobe illustrator for  \n all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 15,
    category: 'Computer',
    status: 'Offline',
  },
  {
    name: 'Development1',
    course: 'Adobe illustrator for  \n all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 16,
    category: 'Teaching',
    status: 'Online',
  },
  {
    name: 'Teaching2',
    course: 'Adobe illustrator for  \n all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 17,
    category: 'Computer',
    status: 'F2F',
  },
  {
    name: 'Computer3',
    course: 'Adobe illustrator for  \n all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 18,
    category: 'Development',
    status: 'Offline',
  },
  {
    name: 'Development2',
    course: 'Adobe illustrator for  \n all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 19,
    category: 'Computer',
    status: 'F2F',
  },
  {
    name: 'Computer2',
    course: 'Adobe illustrator for  \n all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 110,
    category: 'Teaching',
    status: 'Online',
  },
  {
    name: 'Teaching3',
    course: 'Adobe illustrator for  \n all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 111,
    category: 'Development',
    status: 'F2F',
  },
  {
    name: 'Development3',
    course: 'Adobe illustrator for  \n all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 112,
    category: 'Computer',
    status: 'Offline',
  },
];
// };
