export { default as Carouselscreen } from './Authscreens/Carouselscreen';
export { default as Homescreen } from './Appscreens/Homescreen';
export { default as Loginscreen } from './Authscreens/Loginscreen';
export { default as Bottomtab } from './Appscreens/Bottomtab';
export { default as Mycourse } from './Appscreens/Mycourse';
export { default as Register } from './Authscreens/Register';
export { default as Entermail } from './Authscreens/Entermail';
export { default as Otpscreen } from './Authscreens/Otpscreen';
export { default as Resetpass } from './Authscreens/Resetpass';
export { default as Course } from './Appscreens/Course';
// export { default as Tochecklogin } from './Tochecklogin';
// export { default as Loginscreen } from './Loginscreen';
// export { default as Loginscreen } from './Loginscreen';
// export { default as Loginscreen } from './Loginscreen';
// export { default as Loginscreen } from './Loginscreen';
// export { default as Loginscreen } from './Loginscreen';
