export default Data = [
  {
    name: 'Development',
    course: 'Adobe illustrator for  all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 1,
    category: 'Development',
    status: 'Online',
    icon: "code-not-equal-variant"
  },
  {
    name: 'Teaching',
    course: 'Adobe illustrator for all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 2,
    category: 'Buisness',
    status: 'Offline',
    icon: "chart-areaspline"
  },
  {
    name: 'Computer',
    course: 'Adobe illustrator for all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 3,
    category: 'Finance & Accounting',
    icon: "wallet-outline",
    status: 'Online',
  },

  {
    name: 'Teaching1',
    course: 'Adobe illustrator for all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 4,
    status: 'Online',
    category: 'IT & Software',
    icon: "desktop-classic"
  },
  {
    name: 'Computer1',
    course: 'Adobe illustrator for all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 5,
    status: 'Offline',
    category: 'Back Office', 
    icon: "clipboard-list-outline"
  },

  {
    name: 'Development1',
    course: 'Adobe illustrator for all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 6,
    status: 'Online',
    category: 'Personal Development', 
    icon: "account-box" },
  {
    name: 'Teaching2',
    course: 'Adobe illustrator for all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 7,
    status: 'F2F',
    category: 'Graphic & Designing', 
    icon: "pencil-ruler" },
  {
    name: 'Computer3',
    course: 'Adobe illustrator for all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 8,
    status: 'Offline',
    category: 'Marketing', 
    icon: "flag-checkered" },
  {
    name: 'Development2',
    course: 'Adobe illustrator for all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 9,
    status: 'F2F',
    category: 'Video & Photography', 
    icon: "camera" },
  {
    name: 'Computer2',
    course: 'Adobe illustrator for all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 10,
    status: 'Online',
    category: 'Teaching',
    icon: "teach" },
  {
    name: 'Teaching3',
    course: 'Adobe illustrator for all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 11,
    status: 'F2F',
    category: 'Lifestyle', 
    icon: "dog-service" },
  {
    name: 'Development3',
    course: 'Adobe illustrator for all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 12,
    status: 'Offline',
    category: 'Music & instruments', 
    icon: "music" 
    },
  {
    name: 'Development4',
    course: 'Adobe illustrator for all beginner artist',
    Latestcourse: 'Core Java for bignner',
    Coursebranch: 'Programmer',
    Trainer: 'Trainer name',
    rating: '4',
    reviews: ' (432)',
    Price: ' 1999 ',
    Instructor: 'Amit Trivedi',
    price: ' 599.00 ',
    reviews: ' (432)',
    student: ' 4K ',
    id: 13,
    status: 'Offline',
    category: 'Health & Fitness', 
    icon: "heart-pulse" 
    },
];
// };
