export {default as MyCarousel} from './MyCarousel';
export {default as Mybutton} from './Mybutton';
export {default as Loginbutton} from './Loginbutton';
export {default as Socialbutton} from './Socialbutton';
// export { default as Input } from './Input';
export {default as Toinput} from './Toinput';
export {default as MyText} from './MyText';
export {default as ImageBackgrounds} from './ImageBackgrounds';
export {default as Header} from './Header';
export {default as Searchscreen} from './Searchscreen';
export {default as PopularCategory} from './PopularCategory';
export {default as Latestcourse} from './Latestcourse';
export {default as TTrainers} from './TTrainers';
export {default as Prevcourse} from './Prevcourse';
export {default as OtpInput} from './OtpInput';
export { default as Mycourses } from './Mycourses';
export { default as Onlinecourse } from './Onlinecourse';
// export { default as MyText } from './MyText';
// export { default as MyText } from './MyText';
