export { default as Carouselscreen } from './Authscreens/Carouselscreen';
export { default as Homescreen } from './Appscreens/Homescreen';
export { default as Loginscreen } from './Authscreens/Loginscreen';
export { default as Bottomtab } from './Appscreens/Bottomtab';
export { default as Register } from './Authscreens/Register';
export { default as Entermail } from './Authscreens/Entermail';
export { default as Otpscreen } from './Authscreens/Otpscreen';
export { default as Resetpass } from './Authscreens/Resetpass';
export { default as Course } from './Appscreens/Course';
export { default as Mycourse } from './Appscreens/Mycourse';
// export { default as Course } from './Appscreens/Course';
// export { default as Course } from './Appscreens/Course';
export { default as Certificates } from './Appscreens/Drawerscreens/Certificates';
export { default as Faq } from './Appscreens/Drawerscreens/Faq';
export { default as Mycart } from './Appscreens/Drawerscreens/Mycart';
export { default as Myenrollments } from './Appscreens/Drawerscreens/Myenrollments';
export { default as Myquizes } from './Appscreens/Drawerscreens/Myquizes';
export { default as Notifications } from './Appscreens/Drawerscreens/Notifications';
export { default as Offers } from './Appscreens/Drawerscreens/Offers';
export { default as Share } from './Appscreens/Drawerscreens/Share';
export { default as Favourite } from './Appscreens/Drawerscreens/Favourite';
export { default as Myprofile } from './Appscreens/Drawerscreens/Myprofile';
// export { default as Certificates } from './Appscreens/Drawerscreens/Certificates';
// export { default as Certificates } from './Appscreens/Drawerscreens/Certificates';
// export { default as Certificates } from './Appscreens/Drawerscreens/Certificates';
